#!/bin/bash

set -e

swift build \
 -Xswiftc -I$NJS/src \
 -Xswiftc -I$NJS/build \
 -Xlinker $NJS/build/libnjs.a

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/NJS/EmbeddingLanguage
.build/debug/Tests/NJS/EmbeddingValue
